name: Hourly GitHub Archive Data Ingest

on:
  # schedule:
    # Run at minute 5 of every hour
    # - cron: '5 * * * *'
  workflow_dispatch:  # Allow manual triggering
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no data will be written)'
        required: false
        type: boolean
        default: false

# Add concurrency control to prevent overlapping runs
concurrency:
  group: github-archive-ingest
  cancel-in-progress: false

jobs:
  ingest-github-events:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1
      TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}
      TINYBIRD_HOST: ${{ secrets.TINYBIRD_HOST }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl https://tinybird.co | sh
          pip install -e gharchive-to-iceberg
      
      - name: Make script executable
        run: chmod +x gharchive-to-iceberg/ingest_missing_hours.sh
        
      # Combined step for both normal and dry-run modes
      - name: Run data ingestion script
        run: |
          cd gharchive-to-iceberg
          if [ "${{ inputs.dry_run }}" == "true" ]; then
            echo "Running in dry-run mode"
            ./ingest_missing_hours.sh --dry-run
          else
            echo "Running in normal mode"
            ./ingest_missing_hours.sh
            
            # Only copy data to Tinybird if not in dry-run mode
            cd ..
            tb --token $TINYBIRD_TOKEN --host $TINYBIRD_HOST --cloud copy run cp_github_events_rt --wait
          fi 
